version: "3.9"
services:
  app:
    image: go-webapp
    restart: always
    environment:   
      DB_DSN: "postgres://wheels:wheels@storage:5432/wheels"
    ports:
      - 8080:5000
  storage:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "wheels"
      POSTGRES_USER: "wheels"
      POSTGRES_PASSWORD: "wheels"
    ports:
      - "5432:5432"
    volumes:
      - storage:/docker-entrypoint-initdb.d

volumes:
  storage:
