Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "centos-slave"

  config.vm.provider "virtualbox" do |v|
    v.name = "centos-slave-1"
    v.memory = 1024
    v.cpus = 2
  end

  config.ssh.host = "127.0.0.1"
  config.ssh.port = 4444
  config.vm.network "forwarded_port", guest: 22, host: 4444
end
